n = int(input())
st = list(input())
h = int(st.count('h')//2)
a = int(st.count('a')//2)
c = int(st.count('c'))
k = int(st.count('k'))
e = int(st.count('e')//2)
r = int(st.count('r')//2)
t = int(st.count('t'))
print(min(h,a,c,k,e,r,t))